### ISSUE TITLE
Support with extra files

### ISSUE THREAD

**Issue by Vehzx** [klinbee/Survival-Islands-World-Generation#1]
Hi, on the off chance you see this, I just watched the video you made on this survival islands datapack, in the description it says tutorial on how to use the extra files presets will come in a future video but that never happened. I am wondering if I could get some help in how to use the different presets?

Thanks!

**Comment by klinbee** [comment]
Yeahh, essentially I was going to do this mainly because it was a part of other data packs I've made as well (extra files you can change) but I ended up removing those from most of them (because they are hard to keep up with for future changes).

Also, I'm working on a worldgen tutorial series in general, so I felt that having that would work.

BUT if you want to know just in general, basically in the Extra Files, you look for the preset you want, find that file in the base data pack file, and then replace it with the one you actually want to use.

**Comment by Vehzx** [comment]
thank you so much
